<?php

return [
    'replace-url' => 'remont-',
    'adminEmail' => 'admin@example.com',
    'regions' => [
        1 => ['id' => 1, 'title' => 'Москва и область', 'phone' => '8 (499) 450-90-08', 'titleRod' => 'Москве', 'class' => 'moskva'],
        2 => ['id' => 2, 'title' => 'Санкт-Петербург', 'phone' => '8 (812) 643-21-07', 'titleRod' => 'Санкт-Петербурге', 'class' => 'spb'],
    ],
    'siteConfigs' => [
        'remontkofe' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            'stickyMenu' => true,
            'mono' => false,
            'id' => 1,
            'sitePrefix' => 'remont',
        ],
        'spb-remont-kofe' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => false,
            'id' => 2,
            'sitePrefix' => 'spb-kofe',
            'change-logo' => true,
        ],
        'support-delonghi' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13292,
            'id' => 3,
            'sitePrefix' => 'delonghi',
            'change-logo' => true,
        ],
        'support-saeco' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13332,
            'id' => 4,
            'sitePrefix' => 'saeco',
            'change-logo' => true,
        ],
        'philips-coffee-service' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13238,
            'id' => 5,
            'sitePrefix' => 'philips',
            'change-logo' => true,
        ],
        'service-jura' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13202,
            'id' => 6,
            'sitePrefix' => 'jura',
            'change-logo' => true,
        ],
        'support-bosch' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13182,
            'id' => 7,
            'sitePrefix' => 'bosch',
            'change-logo' => true,
        ],
        'service-krups' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13169,
            'id' => 8,
            'sitePrefix' => 'krups',
            'change-logo' => true,
        ],
        'support-melitta' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13231,
            'id' => 9,
            'sitePrefix' => 'melitta',
            'change-logo' => true,
        ],
        'service-nivona' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13682,
            'id' => 10,
            'sitePrefix' => 'nivona',
            'change-logo' => true,
        ],
        'service-siemens' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13777,
            'id' => 11,
            'sitePrefix' => 'siemens',
            'change-logo' => true,
        ],
        'support-gaggia' => [
           'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13527,
            'id' => 12,
            'sitePrefix' => 'gaggia',
            'change-logo' => true,
        ],
        'wmf-service' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13868,
            'id' => 13,
            'sitePrefix' => 'wmf',
            'change-logo' => true,
        ],
        'la-chimbali-remont' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13607,
            'id' => 14,
            'sitePrefix' => 'cimbali',
            'change-logo' => true,
        ],
        'schaerer-service' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13746,
            'id' => 15,
            'sitePrefix' => 'schaerer',
            'change-logo' => true,
        ],
        'frankie-service' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13537,
            'id' => 16,
            'sitePrefix' => 'franke',
            'change-logo' => true,
        ],
        'remont-faema' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13499,
            'id' => 17,
            'sitePrefix' => 'faema',
            'change-logo' => true,
        ],
        'support-miele' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13650,
            'id' => 18,
            'sitePrefix' => 'miele',
            'change-logo' => true,
        ],
        'rancilio-service' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13694,
            'id' => 19,
            'sitePrefix' => 'rancilio',
            'change-logo' => true,
        ],
        'nuova-simonelli-service' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13670,
            'id' => 20,
            'sitePrefix' => 'simonelli',
            'change-logo' => true,
        ],
        'bork-service' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13368,
            'id' => 21,
            'sitePrefix' => 'bork',
            'change-logo' => true,
        ],
        'promac-service' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13687,
            'id' => 22,
            'sitePrefix' => 'promac',
            'change-logo' => true,
        ],
        'support-delonghi-spb' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13292,
            'id' => 23,
            'sitePrefix' => 'delonghispb',
            'change-logo' => true,
        ],
    ],
];
