<?php

return [
    'adminEmail' => 'admin@example.com',
    'supportEmail' => 'support@example.com',
    'user.passwordResetTokenExpire' => 3600,
    'regions' => [
        1 =>
        ['title' => 'Москва', 'tel' => '8 (495) 646-85-07', 'id' => 1, 'address' => 'ул. Барклая 7, БЦ Рубин, офис 507', 'mode' => 'с 10 до 20 ежедневно'],
        ['title' => 'Санкт-Петербург', 'tel' => '8 (812) 603-41-07', 'id' => 2, 'address' => 'м. Петроградская, ул. Ординарная 21', 'mode' => 'с 10 до 20 ежедневно'],
    //['titttle' => 'Екатеринбург', 'tel' => '+7 495 995-25-03', 'id' => 3],
    ],
    'brandRussianNames' => [
        'Krups' => 'Крупс',
        'Marco' => 'Макро',
        'Bosch' => 'Бош',
        'Jura' => 'Юра',
        'KitchenAid' => 'Китчен Эйд',
        'Melitta' => 'Мелитта',
        'Philips' => 'Филипс',
        'AEG' => 'АЕГ',
        'DeLonghi' => 'Делонги',
        'ANIMO' => 'Анимо',
        'Saeco' => 'Саеко',
        'Ascaso' => 'Аскасо',
        'BORK' => 'Борк',
        'Bianchi' => 'Бианчи',
        'Bezzera' => 'Беззера',
        'Bravilor Bonamat' => 'Бравилор Бонамат',
        'Brasilia' => 'Бразилия',
        'C3' => 'Ц3',
        'C.M.A.' => 'С.М.А.',
        'Carimali' => 'Каримали',
        'Dalla Corte' => 'Далла Корте',
        'Coffee Queen' => 'Кофе Куин',
        'Electrolux' => 'Электролюкс',
        'Elektra' => 'Электра',
        'Diamond' => 'Даймонд',
        'Fagor' => 'Фагор',
        'Faema' => 'Фаема',
        'Fiorenzato' => 'Фиорензато',
        'Fiamma' => 'Фиамма',
        'Expobar' => 'Экспобар',
        'Gaggia' => 'Гаджия',
        'FRANKE' => 'Франке',
        'Futurmat' => 'Футурмат',
        'Gastrorag' => 'Гастрораг',
        'Grimac' => 'Гримак',
        'Iberital' => 'Иберитал',
        'Graef' => 'Граеф',
        'La Marzocco' => 'Ла Марзокко',
        'La San Marco' => 'Ла Сан Марко',
        'La Pavoni' => 'Ла Павони',
        'La Cimbali' => 'Ла Чимбали',
        'LaPicolla' => 'Ла Пиколла',
        'Laretti' => 'Ларетти',
        'Lelit' => 'Лелит',
        'Miele' => 'Миле',
        'Markus' => 'Маркус',
        'Nemox' => 'Немокс',
        'Nuova Simonelli' => 'Нуова Симонелли',
        'Nivona' => 'Нивона',
        'Oursson' => 'Оурсон',
        'Promac' => 'Промак',
        'Quick Mill' => 'Куик Милл',
        'Rancilio' => 'Ранчилио',
        'Philips Saeco' => 'Филипс Саеко',
        'Rotel' => 'Ротел',
        'Reneka' => 'Ренека',
        'Rommelsbacher' => 'Роммельсбахер',
        'Rowenta' => 'Ровента',
        'Schaerer' => 'Шерер',
        'SANREMO' => 'СанРемо',
        'Severin' => 'Северин',
        'Smalvic' => 'Смолвик',
        'Siemens' => 'Сименс',
        'smeg' => 'Смег',
        'Solis' => 'Солис',
        'Spidem' => 'Спидем',
        'SPINEL' => 'Спинел',
        'Victoria Arduino' => 'Виктория Ардуино',
        'Unold' => 'Унолд',
        'Bauknecht' => 'Баукнехт',
        'Zelmer' => 'Зелмер',
        'WMF' => 'ВМФ',
        'Philco' => 'Филко',
        'Candy' => 'Канди',
        'Hotpoint-Ariston' => 'Хотпоин Аристон',
        'Kaiser' => 'Кайзер',
        'TEKA' => 'Тека',
        'Gorenje' => 'Горенье',
        'Gaggenau' => 'Гаггенау',
        'Whirlpool' => 'Вирпул',
        'Asko' => 'Аско',
        'Panasonic' => 'Панасоник',
        'Hoover' => 'Ховер',
        'Kuppersbusch' => 'Купперсбуш',
        'Zigmund &amp; Shtain' => 'Зигмунд Энд Штайн',
        'De Dietrich' => 'Де Дитрих',
        'NEFF' => 'Нефф',
        'Restart' => 'Рестарт',
        'ILVE' => 'Илве',
        'RDL' => 'РДЛ',
        'Blaser Star' => 'Блейзер Стар',
        'Baumatic' => 'Бауматик',
        'Bugatti' => 'Бугатти',
        'Foster' => 'Фостер',
        'Thermoplan' => 'Термоплан',
        'Swissler Royal' => 'Свислер Рояль',
        'Fulgor' => 'Фулгор',
        'Bremer' => 'Бремер',
        'Merol' => 'Мерол',
        'Leran' => 'Леран',
        'RICCI' => 'Ричи',
        'Casadio' => 'Касадио',
        'Egro' => 'Егро',
        'Java' => 'Ява',
        'TELEFUNKEN' => 'Телефункен',
        'V-ZUG' => 'В-Зуг',
        'CEBO' => 'Цебо',
        'Inventum' => 'Инвентум',
        'Solac' => 'Солак',
        'BERTAZZONI' => 'Бертаззони',
        'Catler' => 'Кэтлер',
        'Kaffit.com' => 'Каффит',
        'BELTRATTO' => 'Бельтратто',
        'Italco' => 'Италко',
        'Colet' => 'Колет',
        'Bartscher' => 'Бартшер',
        'Gino' => 'Гино',
        'Hurakan' => 'Хуракан',
    ],
    'siteConfigs' => [
        'remontkofe' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            'stickyMenu' => true,
            'mono' => false,
            'id' => 1,
            'sitePrefix' => 'remont',
            'region-sel' => true,
            'category_id' => 7,
            'order-title' => 'МСК Заречная',
        ],
        'spb-remont-kofe' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 701-00-02',
            'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => false,
            'id' => 2,
            'sitePrefix' => 'spb-kofe',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'СПБ Садовая',
        ],
        'support-delonghi' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13292,
            'id' => 3,
            'sitePrefix' => 'delonghi',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'support-saeco' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13332,
            'id' => 4,
            'sitePrefix' => 'saeco',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'philips-coffee-service' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13238,
            'id' => 5,
            'sitePrefix' => 'philips',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'service-jura' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13202,
            'id' => 6,
            'sitePrefix' => 'jura',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'support-bosch' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13182,
            'id' => 7,
            'sitePrefix' => 'bosch',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'service-krups' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13169,
            'id' => 8,
            'sitePrefix' => 'krups',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'support-melitta' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13231,
            'id' => 9,
            'sitePrefix' => 'melitta',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'service-nivona' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13682,
            'id' => 10,
            'sitePrefix' => 'nivona',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'service-siemens' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13777,
            'id' => 11,
            'sitePrefix' => 'siemens',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'support-gaggia' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13527,
            'id' => 12,
            'sitePrefix' => 'gaggia',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'wmf-service' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13868,
            'id' => 13,
            'sitePrefix' => 'wmf',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'la-cimbali-center' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13607,
            'id' => 14,
            'sitePrefix' => 'cimbali',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'schaerer-service' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13746,
            'id' => 15,
            'sitePrefix' => 'schaerer',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'franke-service-center' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13537,
            'id' => 16,
            'sitePrefix' => 'franke',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'remont-faema' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13499,
            'id' => 17,
            'sitePrefix' => 'faema',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'support-miele' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13650,
            'id' => 18,
            'sitePrefix' => 'miele',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'rancilio-service' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13694,
            'id' => 19,
            'sitePrefix' => 'rancilio',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'nuova-simonelli-service' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13670,
            'id' => 20,
            'sitePrefix' => 'simonelli',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'bork-service' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13368,
            'id' => 21,
            'sitePrefix' => 'bork',
            'change-logo' => true,
            'category_id' => 7,
            'order-title' => 'МСК Войковская',
        ],
        'promac-service' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 643-21-07',
            //'spb-multi' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13687,
            'id' => 22,
            'sitePrefix' => 'promac',
            'category_id' => 7,
            'change-logo' => true,
            'order-title' => 'МСК Войковская',
        ],
        'repair-delonghi' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13292,
            'id' => 23,
            'sitePrefix' => 'delonghispb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'saeco-repair' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13332,
            'id' => 24,
            'sitePrefix' => 'saecospb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'philips-help' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13238,
            'id' => 25,
            'sitePrefix' => 'philipsspb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'jura-fix' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13202,
            'id' => 26,
            'sitePrefix' => 'juraspb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'repair-bosch' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13182,
            'id' => 27,
            'sitePrefix' => 'boschspb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'support-krups' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13169,
            'id' => 28,
            'sitePrefix' => 'krupsspb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'repair-melitta' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13231,
            'id' => 29,
            'sitePrefix' => 'melittaspb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'nivona-repair' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13682,
            'id' => 30,
            'sitePrefix' => 'nivonaspb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'siemens-help' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13777,
            'id' => 31,
            'sitePrefix' => 'siemensspb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'gaggia-fix' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13527,
            'id' => 32,
            'sitePrefix' => 'gaggiaspb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'service-wmf' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13868,
            'id' => 33,
            'sitePrefix' => 'wmfspb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'remont-la-cimbali' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13607,
            'id' => 34,
            'sitePrefix' => 'cimbalispb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'schaerer-remont' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13746,
            'id' => 35,
            'sitePrefix' => 'schaererspb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'franke-remont' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13537,
            'id' => 36,
            'sitePrefix' => 'frankespb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'faema-remont' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13499,
            'id' => 37,
            'sitePrefix' => 'faemaspb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'miele-fix' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13650,
            'id' => 38,
            'sitePrefix' => 'mielespb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'remont-rancilio' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13694,
            'id' => 39,
            'sitePrefix' => 'ranciliospb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'remont-nuova-simonelli' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13670,
            'id' => 40,
            'sitePrefix' => 'simonellispb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'support-bork' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13368,
            'id' => 41,
            'sitePrefix' => 'borkspb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'remont-promac' => [
            'phone-1' => '8 (495) 152-00-02',
            'phone-2' => '8 (812) 416-00-01',
            'spb' => true,
            'stickyMenu' => false,
            'mono' => true,
            'brand-id' => 13687,
            'id' => 42,
            'sitePrefix' => 'promacspb',
            'category_id' => 7,
            'order-title' => 'СПБ ТЦ ПИК',
        //'change-logo' => true,
        ],
        'repair-mobiles' => [
            'phone-1' => '8 (495) 181-00-07',
            'phone-2' => '8 (812) 701-00-02',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 43,
            'sitePrefix' => 'spb-mobe',
            '1-line' => false,
            'category_id' => 1,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
        ],
        'repair-laptops' => [
            'phone-1' => '8 (495) 181-00-07',
            'phone-2' => '8 (812) 701-00-02',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 44,
            'sitePrefix' => 'laprops',
            '1-line' => false,
            'category_id' => 3,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
        ],
        'repair-watch' => [
            'phone-1' => '8 (495) 181-00-07',
            'phone-2' => '8 (812) 701-00-02',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 45,
            'sitePrefix' => 'watch',
            '1-line' => false,
            'category_id' => 4,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
        ],
        'tablets-repair' => [
            'phone-1' => '8 (495) 181-00-07',
            'phone-2' => '8 (812) 701-00-02',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 46,
            'sitePrefix' => 'tablets',
            '1-line' => false,
            'category_id' => 2,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
        ],
        'repair-cameras' => [
            'phone-1' => '8 (495) 181-00-07',
            'phone-2' => '8 (812) 701-00-02',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 47,
            'sitePrefix' => 'cameras',
            '1-line' => true,
            'category_id' => 5,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
        ],
        'ifixme' => [
            'phone-1' => '8 (495) 181-00-07',
            'phone-2' => '8 (812) 701-00-02',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 48,
            'sitePrefix' => 'ifixme',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'ifixme',
            'multi_category' => true
        ],
        'remont' => [
            'phone-1' => '8 (495) 323-90-09',
            'phone-2' => '8 (812) 643-21-07',
            'stickyMenu' => true,
            'mono' => false,
            'id' => 49,
            'sitePrefix' => 'remont_coffee',
            'region-sel' => true,
            'category_id' => 7,
            'theme' => 'remont_coffee',
            'order-title' => 'МСК Заречная',
        ],
        'kofe03' => [
            'phone-1' => '8 (495) 135-00-03',
            'phone-2' => '8 (812) 643-21-07',
            'stickyMenu' => true,
            'mono' => false,
            'id' => 50,
            'sitePrefix' => 'kofe03',
            'region-sel' => true,
            'category_id' => 7,
            'theme' => 'kofe03',
            'order-title' => 'МСК Студенческая',
            'jsFiles' => [
                'jquery-1.11.3.min.js',
                'yii.activeForm.js',
                'yii.js',
                'jquery.inputmask.bundle.js',
                'yii.validation.js',
                'jquery.cookie.js',
                'plugins.js',
                'sly.min.js',
                'swiper.jquery.min.js',
                'jquery-ui.js',
                'common.js'
            ],
            'mainJSFileName' => 'scripts',
            'css' => [
                'files' => [
                    'swiper.min.css',
                    'styles.css',
                    'sity.css',
                    'jquery-ui.css',
                    'spb.css',
                ],
                'replaceClasses' => false,
                'mainFileName' => 'all'
            ],
        ],
        'coffee-help' => [
            'phone-1' => '<span class="header-phone-code-part">8 (495) </span> <span class="header-phone-number-part">152-07-07</span>',
            'phone-2' => '8 (812) 643-21-07',
            'stickyMenu' => true,
            'mono' => false,
            'id' => 51,
            'sitePrefix' => 'coffeHelp',
            'region-sel' => true,
            'category_id' => 7,
            'theme' => 'coffeHelp',
            'order-title' => 'help',
        ],
        'fixkofe' => [
            'phone-1' => '8 (812) 501-20-02',
            'phone-2' => '8 (812) 501-20-02',
            'stickyMenu' => true,
            'mono' => false,
            'id' => 52,
            'sitePrefix' => 'fixkofe',
            'region-sel' => true,
            'category_id' => 7,
            'theme' => 'kofe03',
            'order-title' => 'fixkofe',
            'spb' => true,
            'jsFiles' => [
                'jquery-1.11.3.min.js',
                'yii.activeForm.js',
                'yii.js',
                'jquery.inputmask.bundle.js',
                'yii.validation.js',
                'jquery.cookie.js',
                'plugins.js',
                'sly.min.js',
                'swiper.jquery.min.js',
                'jquery-ui.js',
                'common.js'
            ],
            'mainJSFileName' => 'scripts',
        ],
        'coffee-support' => [
            'phone-1' => '<span class="header-phone-code-part">8 (812) </span> <span class="header-phone-number-part">603-50-05</span>',
            'phone-2' => '<span class="header-phone-code-part">8 (812) </span> <span class="header-phone-number-part">603-50-05</span>',
            'stickyMenu' => true,
            'mono' => false,
            'id' => 53,
            'sitePrefix' => 'coffeHelp',
            'region-sel' => true,
            'category_id' => 7,
            'theme' => 'coffeHelp',
            'order-title' => 'support',
            'spb' => true,
        ],
        'spb.remont' => [
            'phone-1' => '8 (812) 612-01-07',
            'phone-2' => '8 (812) 612-01-07',
            'stickyMenu' => true,
            'mono' => false,
            'id' => 54,
            'sitePrefix' => 'remont_coffee',
            'region-sel' => true,
            'category_id' => 7,
            'theme' => 'remont_coffee',
            'order-title' => 'МСК Заречная',
            'spb' => true,
        ],
        'bosch.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 55,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 1,
        ],
        'delonghi.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 56,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 2,
        ],
        'krups.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 57,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 3,
        ],
        'philips.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 58,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 4,
        ],
        'saeco.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 59,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 5,
        ],
        'siemens.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 60,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 6,
        ],
        'miele.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 61,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 7,
        ],
        'jura.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 62,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 8,
        ],
        'bork.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 63,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 9,
        ],
        'schaerer.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 64,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 10,
        ],
        'gaggia.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 65,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 11,
        ],
        'franke.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 66,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 12,
        ],
        'nuova-simonelli.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 67,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 13,
        ],
        'melitta.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 68,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 14,
        ],
        'la-cimbali.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 69,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 15,
        ],
        'promac.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 70,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 16,
        ],
        'faema.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 71,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 17,
        ],
        'rancilio.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 72,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 18,
        ],
        'nivona.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 73,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 19,
        ],
        'wmf.service-center' => [
            'phone-1' => '8 (495) 320-80-08',
            'phone-2' => '8 (495) 320-80-08',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 74,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicat',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 20,
        ],
        /* 'delonghi-service-center' => [
          'phone-1' => '8 (495) 181-00-07',
          'phone-2' => '8 (812) 701-00-02',
          'urlSlash' => true,
          'mono' => false,
          'id' => 75,
          'sitePrefix' => 'multi_cat',
          'order-title' => 'МСК ЗАРЕЧНАЯ',
          'theme' => 'multicatX',
          'multi_category' => true,
          'mono-brand' => true,
          'brand-id' => 2,
          'foreign_category' => true,
          'category_id' => 0,
          ], */
        'bosch-support' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 76,
            'sitePrefix' => 'multi_cat2',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 1,
        ],
        'delonghi-center' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 77,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 2,
        ],
        'krups-remont' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 78,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 3,
        ],
        'philips-center' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 79,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 4,
        ],
        'saeco-center' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 80,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 5,
        ],
        'support-siemens' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 81,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 6,
        ],
        'miele-remont-center' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 82,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 7,
        ],
        'support-jura' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 83,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 8,
        ],
        'bork-services' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 84,
            'sitePrefix' => 'multi_cat2',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 9,
        ],
        'service-center-schaerer' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 85,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 10,
        ],
        'gaggia-center' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 86,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 11,
        ],
        'service-center-franke' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 87,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 12,
        ],
        'nuova-simonelli-remont' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 88,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 13,
        ],
        'melitta-center' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 89,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 14,
        ],
        'service-center-la-cimbali' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 90,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 15,
        ],
        'service-center-promac' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 91,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 16,
        ],
        'service-center-faema' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 92,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 17,
        ],
        'service-center-rancilio' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 93,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 18,
        ],
        'nivona-center' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 94,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 19,
        ],
        'wmf-center' => [
            'phone-1' => '8 (812) 648-38-08',
            'phone-2' => '8 (812) 648-38-08',
            'spb' => true,
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 95,
            'sitePrefix' => 'multi_cat',
            '1-line' => false,
            'category_id' => 0,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 20,
        ],
        'remont-camera' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            'stickyMenu' => true,
            'mono' => false,
            'id' => 96,
            'sitePrefix' => 'kofe03',
            'region-sel' => true,
            'category_id' => 5,
            'theme' => 'kofe03',
            'order-title' => 'МСК Заречная',
            //'spb' => true,
            'jsFiles' => [
                'jquery-1.11.3.min.js',
                'yii.activeForm.js',
                'yii.js',
                'jquery.inputmask.bundle.js',
                'yii.validation.js',
                'jquery.cookie.js',
                'plugins.js',
                'sly.min.js',
                'swiper.jquery.min.js',
                'jquery-ui.js',
                'common.js'
            ],
            'mainJSFileName' => 'scripts',
        ],
        'mobiremo' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            'stickyMenu' => true,
            'mono' => false,
            'id' => 97,
            'sitePrefix' => 'kofe03',
            'region-sel' => true,
            'category_id' => 1,
            'theme' => 'kofe03',
            'order-title' => 'МСК Заречная',
            //'spb' => true,
            'jsFiles' => [
                'jquery-1.11.3.min.js',
                'yii.activeForm.js',
                'yii.js',
                'jquery.inputmask.bundle.js',
                'yii.validation.js',
                'jquery.cookie.js',
                'plugins.js',
                'sly.min.js',
                'swiper.jquery.min.js',
                'jquery-ui.js',
                'common.js'
            ],
            'mainJSFileName' => 'scripts',
        ],
        'remonts-noutbukov' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            'stickyMenu' => true,
            'mono' => false,
            'id' => 98,
            'sitePrefix' => 'kofe03',
            'region-sel' => true,
            'category_id' => 3,
            'theme' => 'kofe03',
            'order-title' => 'МСК Заречная',
            //'spb' => true,
            'jsFiles' => [
                'jquery-1.11.3.min.js',
                'yii.activeForm.js',
                'yii.js',
                'jquery.inputmask.bundle.js',
                'yii.validation.js',
                'jquery.cookie.js',
                'plugins.js',
                'sly.min.js',
                'swiper.jquery.min.js',
                'jquery-ui.js',
                'common.js'
            ],
            'mainJSFileName' => 'scripts',
        ],
        'remont-tablets' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            'stickyMenu' => true,
            'mono' => false,
            'id' => 99,
            'sitePrefix' => 'kofe03',
            'region-sel' => true,
            'category_id' => 2,
            'theme' => 'kofe03',
            'order-title' => 'МСК Заречная',
            //'spb' => true,
            'jsFiles' => [
                'jquery-1.11.3.min.js',
                'yii.activeForm.js',
                'yii.js',
                'jquery.inputmask.bundle.js',
                'yii.validation.js',
                'jquery.cookie.js',
                'plugins.js',
                'sly.min.js',
                'swiper.jquery.min.js',
                'jquery-ui.js',
                'common.js'
            ],
            'mainJSFileName' => 'scripts',
        ],
        'remont-watch' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            'stickyMenu' => true,
            'mono' => false,
            'id' => 100,
            'sitePrefix' => 'kofe03',
            'region-sel' => true,
            'category_id' => 4,
            'theme' => 'kofe03',
            'order-title' => 'МСК Заречная',
            //'spb' => true,
            'jsFiles' => [
                'jquery-1.11.3.min.js',
                'yii.activeForm.js',
                'yii.js',
                'jquery.inputmask.bundle.js',
                'yii.validation.js',
                'jquery.cookie.js',
                'plugins.js',
                'sly.min.js',
                'swiper.jquery.min.js',
                'jquery-ui.js',
                'common.js'
            ],
            'mainJSFileName' => 'scripts',
        ],
        'remont-proektor' => [
            'phone-1' => '8 (499) 450-90-08',
            'phone-2' => '8 (812) 643-21-07',
            'stickyMenu' => true,
            'mono' => false,
            'id' => 101,
            'sitePrefix' => 'kofe03',
            'region-sel' => true,
            'category_id' => 8,
            'theme' => 'kofe03',
            'order-title' => 'МСК Заречная',
            //'spb' => true,
            'jsFiles' => [
                'jquery-1.11.3.min.js',
                'yii.activeForm.js',
                'yii.js',
                'jquery.inputmask.bundle.js',
                'yii.validation.js',
                'jquery.cookie.js',
                'plugins.js',
                'sly.min.js',
                'swiper.jquery.min.js',
                'jquery-ui.js',
                'common.js'
            ],
            'mainJSFileName' => 'scripts',
        ],
        'bosch-fix' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 102,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 1,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'delonghi-service-center' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 103,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 2,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'krups-service-center' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 104,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 3,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'philips-fix' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 105,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 4,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'saeco-service-center' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 106,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 5,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'siemens-repair' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 107,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 6,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'service-centre-miele' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 108,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 7,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'jura-service-center' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 109,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 8,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'bork-center' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 110,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 9,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'schaerer-center' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 111,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 10,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'gaggia-service-center' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 112,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 11,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'franke-center' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 113,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 12,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'nuova-simonelli-support' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 114,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 13,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'melitta-service-center' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 115,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 14,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'la-cimbali-support' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 116,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 15,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'promac-center' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 117,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 16,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'faema-center' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 118,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 17,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'rancilio-center' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 119,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 19,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'wmf-remont' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 120,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 20,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'proektor-service' => [
            'phone-1' => '8 (495) 432-00-20',
            'phone-2' => '8 (812) 701-00-02',
            'stickyMenu' => false,
            'change-logo' => true,
            'mono' => false,
            'id' => 121,
            'sitePrefix' => 'proektor',
            '1-line' => false,
            'category_id' => 3,
            'order-title' => 'МСК ЗАРЕЧНАЯ',
        ],
        'new-sites' => [
            'phone-1' => '8 (495) 181-00-07',
            'phone-2' => '8 (812) 701-00-02',
            'urlSlash' => true,
            'mono' => false,
            'id' => 122,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatXspb',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 20,
            'foreign_category' => true,
            'category_id' => 0,
            'spb' => true,
        ],
        'nivona-service-center' => [
            'phone-1' => '8 (495) 185-08-00',
            'phone-2' => '8 (495) 185-08-00',
            'urlSlash' => true,
            'mono' => false,
            'id' => 123,
            'sitePrefix' => 'multi_cat',
            'order-title' => 'МСК ЗАРЕЧНАЯ',
            'theme' => 'multicatX',
            'multi_category' => true,
            'mono-brand' => true,
            'brand-id' => 19,
            'foreign_category' => true,
            'category_id' => 0,
        ],
        'kofemashin-remont' => [
            'phone-1' => '8 (495) 323-90-09',
            'phone-2' => '8 (812) 643-21-07',
            'stickyMenu' => true,
            'mono' => false,
            'id' => 124,
            'sitePrefix' => 'professionals',
            'region-sel' => true,
            'category_id' => 7,
            'theme' => 'professionals',
            'order-title' => 'МСК Заречная',
        ],
        'kofemashina-service' => [
            'phone-1' => '8 (495) 323-90-09',
            'phone-2' => '8 (812) 643-21-07',
            'stickyMenu' => true,
            'mono' => false,
            'id' => 125,
            'sitePrefix' => 'professionalsSpb',
            'region-sel' => true,
            'category_id' => 7,
            'theme' => 'professionals',
            'order-title' => 'МСК Заречная',
            'spb' => true,
        ],
    ]
];
