<?php

return [
    50 => ['http://kofe03.ru/remont-kofemashin-c3' => 'http://kofe03.ru'],
    53 => [
        'http://coffee-support.ru/uslugi-i-ceny' => 'http://coffee-support.ru/price',
        'http://coffee-support.ru/brendy' => 'http://coffee-support.ru/brands'
    ],
    124 => [
        'http://kofemashin-remont.ru/repair-delonghi/esam-3500/kompleksnaya-profilaktika' => 'http://kofemashin-remont.ru/repair-delonghi',
        'http://kofemashin-remont.ru/repair-saeco/aroma-sm-400/remont-kapuchinatora' => 'http://kofemashin-remont.ru/repair-saeco',
        'http://kofemashin-remont.ru/repair-jura/impressa-c9-one-touch/chistka-ot-kofeinykh-masel' => 'http://kofemashin-remont.ru/repair-jura',
        'http://kofemashin-remont.ru/repair-jura/giga-x7c-professional/remont-nasosa' => 'http://kofemashin-remont.ru/repair-jura',
        'http://kofemashin-remont.ru/repair-saeco/hd-8762/zamena-modulya-upravleniya' => 'http://kofemashin-remont.ru/repair-saeco',
        'http://kofemashin-remont.ru/repair-saeco/hd-8664/zamena-modulya-upravleniya' => 'http://kofemashin-remont.ru/repair-saeco',
        'http://kofemashin-remont.ru/repair-saeco/odea-giro-v2/dostavka-kofemashiny' => 'http://kofemashin-remont.ru/repair-saeco',
        'http://kofemashin-remont.ru/repair-krups/121-aromacafe/dostavka-kofemashiny' => 'http://kofemashin-remont.ru/repair-krups',
        'http://kofemashin-remont.ru/repair-gaggia/new-baby/ne-molet-kofe' => 'http://kofemashin-remont.ru/repair-gaggia',
        'http://kofemashin-remont.ru/repair-jura/impressa-j9-4-one-touch-tft/remont-nasosa' => 'http://kofemashin-remont.ru/repair-jura',
        'http://kofemashin-remont.ru/repair-krups/nespresso-umat-xn2505/zamena-uplotnitelnogo-koltsa-gruppy' => 'http://kofemashin-remont.ru/repair-krups',
        'http://kofemashin-remont.ru/repair-jura/e8-chrome/remont-kofemolki' => 'http://kofemashin-remont.ru/repair-jura',
        'http://kofemashin-remont.ru/repair-saeco/hd-8953/zamena-mikrovyklyuchatelei' => 'http://kofemashin-remont.ru/repair-saeco',
        'http://kofemashin-remont.ru/repair-animo/mt100/ne-delaet-kofe' => 'http://kofemashin-remont.ru',
        'http://kofemashin-remont.ru/repair-siemens/te806501de/remont-kapuchinatora' => 'http://kofemashin-remont.ru/repair-siemens',
        'http://kofemashin-remont.ru/repair-smalvic/remont-gidrosistemy' => 'http://kofemashin-remont.ru/repair-bork',
        'http://kofemashin-remont.ru/repair-siemens/tc-40203/kompleksnaya-profilaktika' => 'http://kofemashin-remont.ru/repair-siemens',
        'http://kofemashin-remont.ru/repair-siemens/tc-24001/chistka-ot-kofeinykh-masel' => 'http://kofemashin-remont.ru/repair-siemens',
        'http://kofemashin-remont.ru/repair-delonghi/dc-300-digit/remont-gidrosistemy' => 'http://kofemashin-remont.ru/repair-delonghi',
        'http://kofemashin-remont.ru/repair-saeco/hd-8927/zamena-modulya-upravleniya' => 'http://kofemashin-remont.ru/repair-saeco',
        'http://kofemashin-remont.ru/repair-delonghi/esam-4300/protekaet' => 'http://kofemashin-remont.ru/repair-delonghi',
        'http://kofemashin-remont.ru/repair-foster/zamena-mikrovyklyuchatelei' => 'http://kofemashin-remont.ru/repair-bork',
        'http://kofemashin-remont.ru/repair-reneka/viva-e-1/dostavka-kofemashiny' => 'http://kofemashin-remont.ru/',
        'http://kofemashin-remont.ru/repair-delonghi/es-156-v/zamena-mikrovyklyuchatelei' => 'http://kofemashin-remont.ru/repair-delonghi',
        'http://kofemashin-remont.ru/repair-marco/filtro-flask' => 'http://kofemashin-remont.ru/',
        'http://kofemashin-remont.ru/repair-jura/impressa-c9-one-touch/chistka-ot-kofeinykh-masel' => 'http://kofemashin-remont.ru/repair-jura/impressa-c9-one-touch',
        'http://kofemashin-remont.ru/repair-animo/excelso-t/dostavka-kofemashiny' => 'http://kofemashin-remont.ru/repair-gino'
    ],
    51 => [
        'http://coffee-help.ru/remont-delonghi/nespresso-umilk/dekofenatsiya' => 'https://coffee-help.ru/remont-delonghi',
        'http://coffee-help.ru/remont-bosch/tes-70621-rw/ne-vklyuchaetsya' => 'https://coffee-help.ru/remont-bosch',
        'http://coffee-help.ru/remont-gaggia/babila/net-para' => 'https://coffee-help.ru',
        'http://coffee-help.ru/remont-gaggia/paros/diagnostics' => 'https://coffee-help.ru',
        'http://coffee-help.ru/remont-delonghi/nespresso-umilk/dekofenatsiya' => 'https://coffee-help.ru/remont-delonghi/nespresso-umilk',
        'http://coffee-help.ru/remont-gaggia/babila/net-para' => 'https://coffee-help.ru/remont-krups',
        'http://coffee-help.ru/remont-sanremo/opera-3-gr/ne-nalivaet-kofe' => 'https://coffee-help.ru',
        'http://coffee-help.ru/remont-gaggia/babila/net-para' => 'https://coffee-help.ru/remont-gaggia',
        'http://coffee-help.ru/remont-bauknecht/kmt-9145-ixl/shipping' => 'https://coffee-help.ru',
        'http://coffee-help.ru/remont-delonghi/icm-65-t/ne-greet-vodu' => 'https://coffee-help.ru/remont-delonghi',
        'http://coffee-help.ru/remont-severin/ka-4770/zamena-zhernovov' => 'https://coffee-help.ru',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/dekaltsinatsiya' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/dekaltsinatsiya',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/zabor-kofemashiny-v-servis' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/zabor-kofemashiny-v-servis',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/zamena-zhernovov' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/zamena-zhernovov',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/zamena-modulya-upravleniya' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/zamena-modulya-upravleniya',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/zamena-uplotnitelnogo-koltsa-gruppy' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/zamena-uplotnitelnogo-koltsa-gruppy',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/remont-gidrosistemy' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/remont-gidrosistemy',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/remont-kofemolki' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/remont-kofemolki',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/chistka-ot-kofeinykh-masel' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/chistka-ot-kofeinykh-masel',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/dekofenatsiya' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/dekofenatsiya',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/diagnostics' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/diagnostics',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/zamena-mikrovyklyuchatelei' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/zamena-mikrovyklyuchatelei',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/zamena-tena' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/zamena-tena',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/kompleksnaya-profilaktika' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/kompleksnaya-profilaktika',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/remont-kapuchinatora' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/remont-kapuchinatora',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/remont-nasosa' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/remont-nasosa',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/shipping' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/shipping',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/ne-vklyuchaetsya' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/ne-vklyuchaetsya',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/net-para' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/net-para',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/protekaet' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/protekaet',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/ne-nalivaet-kofe' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/ne-nalivaet-kofe',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/ne-delaet-kofe' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/ne-delaet-kofe',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/plokho-techet-kofe' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/plokho-techet-kofe',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/kofe-slabyi-i-nevkusnyi' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/kofe-slabyi-i-nevkusnyi',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/ne-podaet-vodu' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/ne-podaet-vodu',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/ne-delaet-penu' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/ne-delaet-penu',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/ne-greet-vodu' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/ne-greet-vodu',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/ne-mеlet-kofe' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/ne-mеlet-kofe',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/vydaet-oshibku' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/vydaet-oshibku',
        'http://coffee-help.ru/remont-expobar/new-elegance-display-control-3gr-copper-damask-wood/kofe-slishkom-kholodnyigoryachii' => 'http://coffee-help.ru/remont-expobar/3gr-copper-damask-wood/kofe-slishkom-kholodnyigoryachii'
    ],
    124 => [
        'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11-one-grinder-doser-one-canister' => 'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11',
        'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11-one-grinder-doser-one-canister/ne-nalivaet-kofe' => 'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11/ne-nalivaet-kofe',
        'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11-one-grinder-doser-one-canister/ne-greet-vodu' => 'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11/ne-greet-vodu',
        'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11-one-grinder-doser-one-canister/ne-podaet-vodu' => 'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11/ne-podaet-vodu',
        'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11-one-grinder-doser-one-canister/ne-molet-kofe' => 'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11/ne-molet-kofe',
        'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11-one-grinder-doser-one-canister/kofe-slabyi-i-nevkusnyi' => 'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11/kofe-slabyi-i-nevkusnyi',
        'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11-one-grinder-doser-one-canister/net-para' => 'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11/net-para',
        'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11-one-grinder-doser-one-canister/kofe-slishkom-kholodnyigoryachii' => 'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11/kofe-slishkom-kholodnyigoryachii',
        'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11-one-grinder-doser-one-canister/ne-vklyuchaetsya' => 'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11/ne-vklyuchaetsya',
        'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11-one-grinder-doser-one-canister/protekaet' => 'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11/protekaet',
        'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11-one-grinder-doser-one-canister/plokho-techet-kofe' => 'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11/plokho-techet-kofe',
        'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11-one-grinder-doser-one-canister/ne-delaet-kofe' => 'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11/ne-delaet-kofe',
        'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11-one-grinder-doser-one-canister/vydaet-oshibku' => 'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11/vydaet-oshibku',
        'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11-one-grinder-doser-one-canister/ne-delaet-penu' => 'http://kofemashin-remont.ru/repair-faema/barcode-chocolate-amp-specialites-milkps11/ne-delaet-penu'
    ]
];
